# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edxDB', '0002_student_enroll_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_ratio', models.FloatField(null=True)),
                ('child_lo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_learning_object', to='edxDB.LearningObject')),
                ('parent_lo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_learning_object', to='edxDB.LearningObject')),
            ],
        ),
    ]
