# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edxDB', '0003_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='children',
            field=models.ManyToManyField(through='edxDB.Dependency', to='edxDB.LearningObject'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='parent_lo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edxDB.LearningObject'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='risk_ratio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
