# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edxDB', '0004_auto_20171108_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='average_score',
            field=models.FloatField(null=True),
        ),
    ]
