# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edxDB', '0005_question_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='questions',
            field=models.ManyToManyField(through='edxDB.Contribution', to='edxDB.Question'),
        ),
        migrations.AddField(
            model_name='learningobject',
            name='total_points',
            field=models.FloatField(null=True),
        ),
    ]
