# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edxDB', '0006_auto_20171112_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='average_points',
            field=models.FloatField(null=True),
        ),
    ]
