# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edxDB', '0007_learningobject_average_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lo_points_json',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
